# create a github build action for openocd on linux
# the event happen when a push or pull request is made to the master branch

name: OpenOCD Linux Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
      # 64bit
      CFALGS: -m64
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf texinfo automake libtool libusb-1.0-0-dev libftdi-dev libhidapi-dev libusb-dev libusb-1.0-0-dev libusb-1.0-doc libusb-1.0-0-dbg libusb-1.0-0 libusb-1.0-0-dev libusb-1.0-doc libusb-1.0-0-dbg libusb-1.0-0 libusb-1.0-0-dev libusb-1.0-doc libusb-1.0-0-dbg libusb-1.0-0 libusb-1.0-0-dev libusb-1.0-doc libusb-1.0-0-dbg libusb-1.0-0 libusb-1.0-0-dev libusb-1.0-doc libusb-1.0-0-dbg libusb-1.0-0 libusb-1.0-0-dev libusb-1.0-doc libusb-1.0-0-dbg libusb-1.0-0 libusb-1.0-0-dev libusb-1.0-doc libusb-1.0-0-dbg libusb-1.0-0 libusb-1.0-0-dev libusb-1.0-doc libusb-1.0-0-dbg libusb-1.0-0 libusb-1.0-0-dev libusb-1.0-doc libusb-1.0-0-dbg libusb-1.0-0 libusb-1.0-0-dev libusb-1.0-doc libusb-1.0-0-dbg libusb-1.0-0 libusb-1.0-0-dev libusb-1.0-doc libusb-1.0-0-dbg libusb-1.0-0 libusb-1.0-0-dev libusb-1.0-doc libusb-1.0-0-dbg libusb-1.0-0 libusb-1.0-0-dev libusb-1
    - run: ./bootstrap
    - run: ./configure
    - run: make
    - run: file src/openocd | grep 64-bit
    - run: ./src/openocd -v
